FROM golang:1.22 AS builder
WORKDIR /backend

COPY . .

ENV GOPROXY=https://goproxy.io/

RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -x -o ./build/main .

FROM alpine:latest
WORKDIR /backend

COPY --from=builder /backend/build/main .

CMD ["./main", "serve"]
