// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package ports

const (
	BearerScopes = "bearer.Scopes"
)

// GetAllCategoryParams defines parameters for GetAllCategory.
type GetAllCategoryParams struct {
	// Page 分页页数
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Num 每页数量
	Num *int `form:"num,omitempty" json:"num,omitempty"`
}

// CreateCategoryJSONBody defines parameters for CreateCategory.
type CreateCategoryJSONBody struct {
	// DisplayName 展示名称
	DisplayName string `json:"displayName"`

	// Name 名称
	Name string `json:"name"`

	// SeoDesc seo描述
	SeoDesc string `json:"seoDesc"`
}

// UpdateCategoryJSONBody defines parameters for UpdateCategory.
type UpdateCategoryJSONBody struct {
	// DisplayName 展示名称
	DisplayName string `json:"displayName"`

	// SeoDesc seo描述
	SeoDesc string `json:"seoDesc"`
}

// CreateCategoryJSONRequestBody defines body for CreateCategory for application/json ContentType.
type CreateCategoryJSONRequestBody CreateCategoryJSONBody

// UpdateCategoryJSONRequestBody defines body for UpdateCategory for application/json ContentType.
type UpdateCategoryJSONRequestBody UpdateCategoryJSONBody
