@startuml
!include lib_eventstorming.puml

Command("CreatePost", "创建")
Command("ModifyPostVisible", "修改可见性")
Command("DeletePost", "删除")
Command("ModifyPostTitle", "修改标题")
Command("ModifyPostDesc", "修改简介")
Command("ResetPostCategory", "重新设置分类")
Command("ModifyPostTags", "修改标签组")
Command("ResetPostContent", "重新设置帖子内容")

Command("CreateCategory", "创建分类")
Command("DeleteCategory", "删除分类")
Command("ModifyCategoryDesc", "修改分类简介")

Person("Admin")
Admin -down-> ResetPostContent
Admin -down-> ModifyPostVisible
Admin -down-> DeletePost
Admin -down-> ResetPostCategory
Admin -down-> CreatePost
Admin -down-> ModifyPostTitle
Admin -down-> ModifyPostDesc
Admin -down-> ModifyPostTags
Admin -down-> CreateCategory
Admin -down-> DeleteCategory
Admin -down-> ModifyCategoryDesc

Aggregate("Post")
CreatePost -down-> Post
ModifyPostVisible -down-> Post
DeletePost -down-> Post
ModifyPostTitle -down-> Post
ModifyPostDesc -down-> Post
ResetPostCategory -down-> Post
ModifyPostTags -down-> Post
ResetPostContent -down-> Post

Aggregate("Category")
CreateCategory -down-> Category
DeleteCategory -down-> Category
ModifyCategoryDesc -down-> Category

@enduml